namespace winUpdateMiniTool;

/// <summary>
///     Provides error messages for Windows Update operations based on error codes.
/// </summary>
internal static class UpdateErrors {
  /// <summary>
  ///     Gets the error message corresponding to the specified error code.
  /// </summary>
  /// <param name="id">The error code.</param>
  /// <returns>The error message associated with the error code.</returns>
  public static string GetErrorStr(uint id) {
    return id switch {
      0x00240001 => "Windows Update Agent was stopped successfully.",
      0x00240002 => "Windows Update Agent updated itself.",
      0x00240003 => "Operation completed successfully but there were errors applying the updates.",
      0x00240004 =>
        "A callback was marked to be disconnected later because the request to disconnect the operation came while a callback was executing.",
      0x00240005 => "The system must be restarted to complete installation of the update.",
      0x00240006 => "The update to be installed is already installed on the system.",
      0x00240007 => "The update to be removed is not installed on the system.",
      0x00240008 => "The update to be downloaded has already been downloaded.",
      0x00240009 =>
        "The operation completed successfully, but some updates were skipped because the system is running on batteries.",
      0x00242015 => "The installation operation for the update is still in progress.",
      0x00245001 => "No operation was required by the server-initiated healing server response.",
      0x00246001 => "The update to be downloaded is already being downloaded.",
      0x80240001 => "Windows Update Agent was unable to provide the service.",
      0x80240002 => "The maximum capacity of the service was exceeded.",
      0x80240003 => "An ID cannot be found.",
      0x80240004 => "The object could not be initialized.",
      0x80240005 => "The update handler requested a byte range overlapping a previously requested range.",
      0x80240006 => "The requested number of byte ranges exceeds the maximum number (2^31 - 1).",
      0x80240007 => "The index to a collection was invalid.",
      0x80240008 => "The key for the item queried could not be found.",
      0x80240009 =>
        "Another conflicting operation was in progress. Some operations such as installation cannot be performed twice simultaneously.",
      0x8024000A => "Cancellation of the operation was not allowed.",
      0x8024000B => "Operation was cancelled.",
      0x8024000C => "No operation was required.",
      0x8024000D => "Windows Update Agent could not find required information in the update's XML data.",
      0x8024000E => "Windows Update Agent found invalid information in the update's XML data.",
      0x8024000F => "Circular update relationships were detected in the metadata.",
      0x80240010 => "Update relationships too deep to evaluate were evaluated.",
      0x80240011 => "An invalid update relationship was detected.",
      0x80240012 => "An invalid registry value was read.",
      0x80240013 => "Operation tried to add a duplicate item to a list.",
      0x80240014 => "Updates requested for install are not installable by caller.",
      0x80240016 =>
        "Operation tried to install while another installation was in progress or the system was pending a mandatory restart.",
      0x80240017 => "Operation was not performed because there are no applicable updates.",
      0x80240018 => "Operation failed because a required user token is missing.",
      0x80240019 => "An exclusive update cannot be installed with other updates at the same time.",
      0x8024001A => "A policy value was not set.",
      0x8024001B => "The operation could not be performed because the Windows Update Agent is self-updating.",
      0x8024001D => "An update contains invalid metadata.",
      0x8024001E => "Operation did not complete because the service or system was being shut down.",
      0x8024001F => "Operation did not complete because the network connection was unavailable.",
      0x80240020 => "Operation did not complete because there is no logged-on interactive user.",
      0x80240021 => "Operation did not complete because it timed out.",
      0x80240022 => "Operation failed for all the updates.",
      0x80240023 => "The license terms for all updates were declined.",
      0x80240024 => "There are no updates.",
      0x80240025 => "Group Policy settings prevented access to Windows Update.",
      0x80240026 => "The type of update is invalid.",
      0x80240027 => "The URL exceeded the maximum length.",
      0x80240028 => "The update could not be uninstalled because the request did not originate from a WSUS server.",
      0x80240029 => "Search may have missed some updates before there is an unlicensed application on the system.",
      0x8024002A => "A component required to detect applicable updates was missing.",
      0x8024002B => "An operation did not complete because it requires a newer version of server.",
      0x8024002C => "A delta-compressed update could not be installed because it required the source.",
      0x8024002D => "A full-file update could not be installed because it required the source.",
      0x8024002E => "Access to an unmanaged server is not allowed.",
      0x8024002F => "Operation did not complete because the DisableWindowsUpdateAccess policy was set.",
      0x80240030 => "The format of the proxy list was invalid.",
      0x80240031 => "The file is in the wrong format.",
      0x80240032 => "The search criteria string was invalid.",
      0x80240033 => "License terms could not be downloaded.",
      0x80240034 => "Update failed to download.",
      0x80240035 => "The update was not processed.",
      0x80240036 => "The object's current state did not allow the operation.",
      0x80240037 => "The functionality for the operation is not supported.",
      0x80240038 => "The downloaded file has an unexpected content type.",
      0x80240039 => "Agent is asked by server to resync too many times.",
      0x80240040 => "WUA API method does not run on Server Core installation.",
      0x80240041 => "Service is not available while sysprep is running.",
      0x80240042 => "The update service is no longer registered with AU.",
      0x80240043 => "There is no support for WUA UI.",
      0x80240044 => "Only administrators can perform this operation on per-machine updates.",
      0x80240045 => "A search was attempted with a scope that is not currently supported for this type of search.",
      0x80240046 => "The URL does not point to a file.",
      0x80240047 => "The operation requested is not supported.",
      0x80240048 => "The featured update notification info returned by the server is invalid.",
      0x80240049 => "The data is out of range.",
      0x8024004A => "Windows Update agent operations are not available while OS setup is running.",
      0x8024004B => "An orphaned downloadjob was found with no active callers.",
      0x8024004C => "An update could not be installed because the system battery power level is too low.",
      0x8024004D => "The downloaded infrastructure file is incorrectly formatted.",
      0x8024004E => "The infrastructure file must be downloaded using strong SSL.",
      0x8024004F => "A discovery call contributed to a non-zero operation count at idle timer shutdown.",
      0x80240050 => "A search call contributed to a non-zero operation count at idle timer shutdown.",
      0x80240051 => "A download call contributed to a non-zero operation count at idle timer shutdown.",
      0x80240052 => "An install call contributed to a non-zero operation count at idle timer shutdown.",
      0x80240053 => "An unspecified call contributed to a non-zero operation count at idle timer shutdown.",
      0x80240054 => "An interactive user cancelled this operation, which was started from the Windows Update Agent UI.",
      0x80240055 =>
        "Automatic Updates cancelled this operation because it applies to an update that is no longer applicable to this computer.",
      0x80240056 => "This version or edition of the operating system doesn't support the needed functionality.",
      0x80240057 =>
        "The requested update download or install handler, or update applicability expression evaluator, is not provided by this Agent plugin.",
      0x80240058 => "The requested serialization version is not supported.",
      0x80240059 => "The current network cost does not meet the conditions set by the network cost policy.",
      0x8024005A =>
        "The call is cancelled because it applies to an update that is hidden (no longer applicable to this computer).",
      0x8024005B =>
        "The call is cancelled because it applies to an update that is invalid (no longer applicable to this computer).",
      0x8024005C => "The specified volume id is invalid.",
      0x8024005D => "The specified volume id is unrecognized by the system.",
      0x8024005E => "The installation extended error code is not specified.",
      0x8024005F => "The installation extended error code is set to general fail.",
      0x80240FFF => "An operation failed due to reasons not covered by another error code.",
      0x80241001 => "Search may have missed some updates because the Windows Installer is less than version 3.1.",
      0x80241002 => "Search may have missed some updates because the Windows Installer is not configured.",
      0x80241003 => "Search may have missed some updates because policy has disabled Windows Installer patching.",
      0x80241004 => "An update could not be applied because the application is installed per-user.",
      0x80241005 => "Search may have missed some updates because the Windows Installer is less than version 3.1.",
      0x80241FFF => "Search may have missed some updates because there was a failure of the Windows Installer.",
      0x80244000 => "WU_E_PT_SOAPCLIENT_* error codes map to the SOAPCLIENT_ERROR enum of the ATL Server Library.",
      0x80244001 =>
        "Same as SOAPCLIENT_INITIALIZE_ERROR - initialization of the SOAP client failed, possibly because of an MSXML installation failure.",
      0x80244002 => "Same as SOAPCLIENT_OUTOFMEMORY - SOAP client failed because it ran out of memory.",
      0x80244003 => "Same as SOAPCLIENT_GENERATE_ERROR - SOAP client failed to generate the request.",
      0x80244004 => "Same as SOAPCLIENT_CONNECT_ERROR - SOAP client failed to connect to the server.",
      0x80244005 =>
        "Same as SOAPCLIENT_SEND_ERROR - SOAP client failed to send a message for reasons of WU_E_WINHTTP_* error codes.",
      0x80244006 => "Same as SOAPCLIENT_SERVER_ERROR - SOAP client failed because there was a server error.",
      0x80244007 =>
        "Same as SOAPCLIENT_SOAPFAULT - SOAP client failed because there was a SOAP fault for reasons of WU_E_PT_SOAP_* error codes.",
      0x80244008 => "Same as SOAPCLIENT_PARSEFAULT_ERROR - SOAP client failed to parse a SOAP fault.",
      0x80244009 => "Same as SOAPCLIENT_READ_ERROR - SOAP client failed while reading the response from the server.",
      0x8024400A => "Same as SOAPCLIENT_PARSE_ERROR - SOAP client failed to parse the response from the server.",
      0x8024400B =>
        "Same as SOAP_E_VERSION_MISMATCH - SOAP client found an unrecognizable namespace for the SOAP envelope.",
      0x8024400C => "Same as SOAP_E_MUST_UNDERSTAND - SOAP client was unable to understand a header.",
      0x8024400D => "Same as SOAP_E_CLIENT - SOAP client found the message was malformed; fix before resending.",
      0x8024400E =>
        "Same as SOAP_E_SERVER - The SOAP message could not be processed due to a server error; resend later.",
      0x8024400F => "There was an unspecified Windows Management Instrumentation (WMI) error.",
      0x80244010 => "The number of round trips to the server exceeded the maximum limit.",
      0x80244011 => "WUServer policy value is missing in the registry.",
      0x80244012 => "Initialization failed because the object was already initialized.",
      0x80244013 => "The computer name could not be determined.",
      0x80244015 =>
        "The reply from the server indicates that the server was changed or the cookie was invalid; refresh the state of the internal cache and retry.",
      0x80244016 => "Same as HTTP status 400 - the server could not process the request due to invalid syntax.",
      0x80244017 => "Same as HTTP status 401 - the requested resource requires user authentication.",
      0x80244018 => "Same as HTTP status 403 - server understood the request, but declined to fulfill it.",
      0x80244019 => "Same as HTTP status 404 - the server cannot find the requested URI (Uniform Resource Identifier).",
      0x8024401A => "Same as HTTP status 405 - the HTTP method is not allowed.",
      0x8024401B => "Same as HTTP status 407 - proxy authentication is required.",
      0x8024401C => "Same as HTTP status 408 - the server timed out waiting for the request.",
      0x8024401D =>
        "Same as HTTP status 409 - the request was not completed due to a conflict with the current state of the resource.",
      0x8024401E => "Same as HTTP status 410 - requested resource is no longer available at the server.",
      0x8024401F => "Same as HTTP status 500 - an error internal to the server prevented fulfilling the request.",
      0x80244020 =>
        "Same as HTTP status 500 - server does not support the functionality required to fulfill the request.",
      0x80244021 =>
        "Same as HTTP status 502 - the server, while acting as a gateway or proxy, received an invalid response from the upstream server it accessed in attempting to fulfill the request.",
      0x80244022 => "Same as HTTP status 503 - the service is temporarily overloaded.",
      0x80244023 => "Same as HTTP status 503 - the request was timed out waiting for a gateway.",
      0x80244024 =>
        "Same as HTTP status 505 - the server does not support the HTTP protocol version used for the request.",
      0x80244025 => "Operation failed due to a changed file location; refresh internal state and resend.",
      0x80244026 =>
        "Operation failed because Windows Update Agent does not support registration with a non-WSUS server.",
      0x80244027 => "The server returned an empty authentication information list.",
      0x80244028 => "Windows Update Agent was unable to create any valid authentication cookies.",
      0x80244029 => "A configuration property value was wrong.",
      0x8024402A => "A configuration property value was missing.",
      0x8024402B =>
        "The HTTP request could not be completed and the reason did not correspond to any of the WU_E_PT_HTTP_* error codes.",
      0x8024402C =>
        "Same as ERROR_WINHTTP_NAME_NOT_RESOLVED - the proxy server or target server name cannot be resolved.",
      0x8024502D =>
        "Windows Update Agent failed to download a redirector cabinet file with a new redirectorId value from the server during the recovery.",
      0x8024502E => "A redirector recovery action did not complete because the server is managed.",
      0x8024402F => "External cab file processing completed with some errors.",
      0x80244030 => "The external cab processor initialization did not complete.",
      0x80244031 => "The format of a metadata file was invalid.",
      0x80244032 => "External cab processor found invalid metadata.",
      0x80244033 => "The file digest could not be extracted from an external cab file.",
      0x80244034 => "An external cab file could not be decompressed.",
      0x80244035 => "External cab processor was unable to get file locations.",
      0x80240436 =>
        "The server does not support category-specific search; Full catalog search has to be issued instead.",
      0x80240437 => "There was a problem authorizing with the service.",
      0x80240438 => "There is no route or network connectivity to the endpoint.",
      0x80240439 => "The data received does not meet the data contract expectations.",
      0x8024043A => "The url is invalid.",
      0x8024043B => "Unable to load NWS runtime.",
      0x8024043C => "The proxy auth scheme is not supported.",
      0x8024043D => "The requested service property is not available.",
      0x8024043E => "The endpoint provider plugin requires online refresh.",
      0x8024043F => "A URL for the requested service endpoint is not available.",
      0x80240440 => "The connection to the service endpoint died.",
      0x80240441 => "The operation is invalid because protocol talker is in an inappropriate state.",
      0x80240442 => "The object is in a faulted state due to a previous error.",
      0x80240443 => "The operation would lead to numeric overflow.",
      0x80240444 => "The operation was aborted.",
      0x80240445 => "The operation was abandoned.",
      0x80240446 => "A quota was exceeded.",
      0x80240447 => "The information was not available in the specified language.",
      0x80240448 => "The address is already being used.",
      0x80240449 => "The address is not valid for this context.",
      0x8024044A => "Unrecognized error occurred in the Windows Web Services framework.",
      0x8024044B => "A security operation failed in the Windows Web Services framework.",
      0x80244FFF => "A communication error not covered by another WU_E_PT_* error code.",
      0x80245001 => "The redirector XML document could not be loaded into the DOM class.",
      0x80245002 => "The redirector XML document is missing some required information.",
      0x80245003 => "The redirectorId in the downloaded redirector cab is less than in the cached cab.",
      0x80245004 => "The service ID is not supported in the service environment.",
      0x80245005 => "The response from the redirector server had an unsupported content type.",
      0x80245006 => "The response from the redirector server had an error status or was invalid.",
      0x80245008 => "The maximum number of name value pairs was exceeded by the attribute provider.",
      0x80245009 => "The name received from the attribute provider was invalid.",
      0x8024500A => "The value received from the attribute provider was invalid.",
      0x8024500B =>
        "There was an error in connecting to or parsing the response from the Service Locator Service redirector server.",
      0x8024500C => "Connections to the redirector server are disallowed by managed policy.",
      0x8024500D => "The redirector would go online but is disallowed by caller configuration.",
      0x802450FF => "The redirector failed for reasons not covered by another WU_E_REDIRECTOR_* error code.",
      0x80245101 => "Verification of the servicing engine package failed.",
      0x80245102 => "Verification of a servicing package failed.",
      0x80245103 => "Verification of the staged engine failed.",
      0x80245104 => "Verification of a staged payload failed.",
      0x80245105 => "An internal error occurred where the servicing action was not found.",
      0x80245106 => "There was a parse error in the service environment response.",
      0x80245107 => "A downloaded file failed an integrity check.",
      0x80245108 => "No engine was provided by the server-initiated healing server response.",
      0x802451FF => "There was a failure for reasons not covered by another WU_E_SIH_* error code.",
      0x8024C001 => "A driver was skipped.",
      0x8024C002 => "A property for the driver could not be found. It may not conform with required specifications.",
      0x8024C003 => "The registry type read for the driver does not match the expected type.",
      0x8024C004 => "The driver update is missing metadata.",
      0x8024C005 => "The driver update is missing a required attribute.",
      0x8024C006 => "Driver synchronization failed.",
      0x8024C007 => "Information required for the synchronization of applicable printers is missing.",
      0x8024C008 => "After installing a driver update, the updated device has reported a problem.",
      0x8024CFFF => "A driver error not covered by another WU_E_DRV_* code.",
      0x80248000 => "An operation failed because Windows Update Agent is shutting down.",
      0x80248001 => "An operation failed because the data store was in use.",
      0x80248002 => "The current and expected states of the data store do not match.",
      0x80248003 => "The data store is missing a table.",
      0x80248004 => "The data store contains a table with unexpected columns.",
      0x80248005 => "A table could not be opened because the table is not in the data store.",
      0x80248006 => "The current and expected versions of the data store do not match.",
      0x80248007 => "The information requested is not in the data store.",
      0x80248008 =>
        "The data store is missing required information or has a NULL in a table column that requires a non-null value.",
      0x80248009 =>
        "The data store is missing required information or has a reference to missing license terms, file, localized property or linked row.",
      0x8024800A => "The update was not processed because its update handler could not be recognized.",
      0x8024800B => "The update was not deleted because it is still referenced by one or more services.",
      0x8024800C => "The data store section could not be locked within the allotted time.",
      0x8024800D =>
        "The category was not added because it contains no parent categories and is not a top-level category itself.",
      0x8024800E => "The row was not added because an existing row has the same primary key.",
      0x8024800F => "The data store could not be initialized because it was locked by another process.",
      0x80248010 => "The data store is not allowed to be registered with COM in the current process.",
      0x80248011 => "Could not create a data store object in another process.",
      0x80248013 => "The server sent the same update to the client with two different revision IDs.",
      0x80248014 => "An operation did not complete because the service is not in the data store.",
      0x80248015 => "An operation did not complete because the registration of the service has expired.",
      0x80248016 =>
        "A request to hide an update was declined because it is a mandatory update or because it was deployed with a deadline.",
      0x80248017 => "A table was not closed because it is not associated with the session.",
      0x80248018 => "A table was not closed because it is not associated with the session.",
      0x80248019 =>
        "A request to remove the Windows Update service or to unregister it with Automatic Updates was declined because it is a built-in service and/or Automatic Updates cannot fall back to another service.",
      0x8024801A => "A request was declined because the operation is not allowed.",
      0x8024801B =>
        "The schema of the current data store and the schema of a table in a backup XML document do not match.",
      0x8024801C => "The data store requires a session reset; release the session and retry with a new session.",
      0x8024801D => "A data store operation did not complete because it was requested with an impersonated identity.",
      0x80248FFF => "A data store error not covered by another WU_E_DS_* code.",
      0x80249001 => "Parsing of the rule file failed.",
      0x80249002 => "Failed to get the requested inventory type from the server.",
      0x80249003 => "Failed to upload inventory result to the server.",
      0x80249004 => "There was an inventory error not covered by another error code.",
      0x80249005 => "A WMI error occurred when enumerating the instances for a particular class.",
      0x8024A000 => "Automatic Updates was unable to service incoming requests.",
      0x8024A002 =>
        "The old version of the Automatic Updates client has stopped because the WSUS server has been upgraded.",
      0x8024A003 => "The old version of the Automatic Updates client was disabled.",
      0x8024A004 => "Automatic Updates was unable to process incoming requests because it was paused.",
      0x8024A005 => "No unmanaged service is registered with AU.",
      0x8024A006 => "The default service registered with AU changed during the search.",
      0x8024A007 => "A reboot is in progress.",
      0x8024A008 => "Automatic Updates can't process incoming requests while Windows Welcome is running.",
      0x8024AFFF => "An Automatic Updates error not covered by another WU_E_AU * code.",
      0x80242000 =>
        "A request for a remote update handler could not be completed because no remote process is available.",
      0x80242001 => "A request for a remote update handler could not be completed because the handler is local only.",
      0x80242002 =>
        "A request for an update handler could not be completed because the handler could not be recognized.",
      0x80242003 => "A remote update handler could not be created because one already exists.",
      0x80242004 =>
        "A request for the handler to install (uninstall) an update could not be completed because the update does not support install (uninstall).",
      0x80242005 => "An operation did not complete because the wrong handler was specified.",
      0x80242006 => "A handler operation could not be completed because the update contains invalid metadata.",
      0x80242007 => "An operation could not be completed because the installer exceeded the time limit.",
      0x80242008 => "An operation being done by the update handler was cancelled.",
      0x80242009 => "An operation could not be completed because the handler-specific metadata is invalid.",
      0x8024200A =>
        "A request to the handler to install an update could not be completed because the update requires user input.",
      0x8024200B => "The installer failed to install (uninstall) one or more updates.",
      0x8024200C =>
        "The update handler should download self-contained content rather than delta-compressed content for the update.",
      0x8024200D => "The update handler did not install the update because it needs to be downloaded again.",
      0x8024200E =>
        "The update handler failed to send notification of the status of the install (uninstall) operation.",
      0x8024200F => "The file names contained in the update metadata and in the update package are inconsistent.",
      0x80242010 => "The update handler failed to fall back to the self-contained content.",
      0x80242011 => "The update handler has exceeded the maximum number of download requests.",
      0x80242012 => "The update handler has received an unexpected response from CBS.",
      0x80242013 => "The update metadata contains an invalid CBS package identifier.",
      0x80242014 => "The post-reboot operation for the update is still in progress.",
      0x80242015 => "The result of the post-reboot operation for the update could not be determined.",
      0x80242016 => "The state of the update after its post-reboot operation has completed is unexpected.",
      0x80242017 => "The OS servicing stack must be updated before this update is downloaded or installed.",
      0x80242018 => "A callback installer called back with an error.",
      0x80242019 => "The custom installer signature did not match the signature required by the update.",
      0x8024201A => "The installer does not support the installation configuration.",
      0x8024201B => "The targeted session for install is invalid.",
      0x8024201C => "The handler failed to decrypt the update files.",
      0x8024201D => "The update handler is disabled until the system reboots.",
      0x8024201E => "The AppX infrastructure is not present on the system.",
      0x8024201F => "The update cannot be committed because it has not been previously installed or staged.",
      0x80242020 => "The specified volume is not a valid AppX package volume.",
      0x80242021 => "The configured default storage volume is unavailable.",
      0x80242022 => "The volume on which the application is installed is unavailable.",
      0x80242023 => "The specified package family is not present on the system.",
      0x80242024 => "Unable to find a package volume marked as system.",
      0x80242FFF => "An update handler error not covered by another WU_E_UH_* code.",
      0x80246001 =>
        "A download manager operation could not be completed because the requested file does not have a URL.",
      0x80246002 => "A download manager operation could not be completed because the file digest was not recognized.",
      0x80246003 =>
        "A download manager operation could not be completed because the file metadata requested an unrecognized hash algorithm.",
      0x80246004 =>
        "An operation could not be completed because a download request is required from the download handler.",
      0x80246005 =>
        "A download manager operation could not be completed because the network connection was unavailable.",
      0x80246006 =>
        "A download manager operation could not be completed because the version of Background Intelligent Transfer Service (BITS) is incompatible.",
      0x80246007 => "The update has not been downloaded.",
      0x80246008 =>
        "A download manager operation failed because the download manager was unable to connect the Background Intelligent Transfer Service (BITS).",
      0x80246009 =>
        "A download manager operation failed because there was an unspecified Background Intelligent Transfer Service (BITS) transfer error.",
      0x8024600A => "A download must be restarted because the location of the source of the download has changed.",
      0x8024600B => "A download must be restarted because the update content changed in a new revision.",
      0x8024600C =>
        "A download failed because the current network limits downloads by update size for the update service.",
      0x8024600E => "The download failed because the client was denied authorization to download the content.",
      0x8024600F => "The download failed because the user token associated with the BITS job no longer exists.",
      0x80246010 => "The sandbox directory for the downloaded update was not found.",
      0x80246011 => "The downloaded update has an unknown file path.",
      0x80246012 => "One or more of the files for the downloaded update is missing.",
      0x80246013 => "An attempt was made to access a downloaded update that has already been removed.",
      0x80246014 => "Windows Update couldn't find a needed portion of a downloaded update's file.",
      0x80246016 =>
        "The download failed because the client was denied authorization to download the content due to no user logged on.",
      0x80246017 => "The download failed because the local user was denied authorization to download the content.",
      0x80246018 => "The download failed because the domain user was denied authorization to download the content.",
      0x80246019 =>
        "The download failed because the MSA account associated with the user was denied authorization to download the content.",
      0x8024601A => "The download will be continued by falling back to BITS to download the content.",
      0x8024601B => "Another caller has requested download to a different volume.",
      0x8024601C => "The hash of the update's sandbox does not match the expected value.",
      0x80246FFF => "There was a download manager error not covered by another WU_E_DM_* error code.",
      0x8024D001 => "Windows Update Agent could not be updated because an INF file contains invalid information.",
      0x8024D002 =>
        "Windows Update Agent could not be updated because the wuident.cab file contains invalid information.",
      0x8024D003 =>
        "Windows Update Agent could not be updated because of an internal error that caused setup initialization to be performed twice.",
      0x8024D004 =>
        "Windows Update Agent could not be updated because setup initialization never completed successfully.",
      0x8024D005 =>
        "Windows Update Agent could not be updated because the versions specified in the INF do not match the actual source file versions.",
      0x8024D006 =>
        "Windows Update Agent could not be updated because a WUA file on the target system is newer than the corresponding source file.",
      0x8024D007 => "Windows Update Agent could not be updated because regsvr32.exe returned an error.",
      0x8024D008 =>
        "An update to the Windows Update Agent was skipped because previous attempts to update have failed.",
      0x8024D009 => "An update to the Windows Update Agent was skipped due to a directive in the wuident.cab file.",
      0x8024D00A =>
        "Windows Update Agent could not be updated because the current system configuration is not supported.",
      0x8024D00B => "Windows Update Agent could not be updated because the system is configured to block the update.",
      0x8024D00C => "Windows Update Agent could not be updated because a restart of the system is required.",
      0x8024D00D => "Windows Update Agent setup is already running.",
      0x8024D00E => "Windows Update Agent setup package requires a reboot to complete installation.",
      0x8024D00F => "Windows Update Agent could not be updated because the setup handler failed during execution.",
      0x8024D010 => "Windows Update Agent could not be updated because the registry contains invalid information.",
      0x8024D011 => "Windows Update Agent must be updated before search can continue.",
      0x8024D012 =>
        "Windows Update Agent must be updated before search can continue. An administrator is required to perform the operation.",
      0x8024D013 =>
        "Windows Update Agent could not be updated because the server does not contain update information for this version.",
      0x8024D014 => "Windows Update Agent is successfully updated, but a reboot is required to complete the setup.",
      0x8024D015 => "Windows Update Agent is successfully updated, but a reboot is required to complete the setup.",
      0x8024D016 => "Windows Update Agent could not be updated because of an unknown error.",
      0x8024DFFF =>
        "Windows Update Agent could not be updated because of an error not covered by another WU_E_SETUP_* error code.",
      0x8024E001 => "An expression evaluator operation could not be completed because an expression was unrecognized.",
      0x8024E002 => "An expression evaluator operation could not be completed because an expression was invalid.",
      0x8024E003 =>
        "An expression evaluator operation could not be completed because an expression contains an incorrect number of metadata nodes.",
      0x8024E004 =>
        "An expression evaluator operation could not be completed because the version of the serialized expression data is invalid.",
      0x8024E005 => "The expression evaluator could not be initialized.",
      0x8024E006 => "An expression evaluator operation could not be completed because there was an invalid attribute.",
      0x8024E007 =>
        "An expression evaluator operation could not be completed because the cluster state of the computer could not be determined.",
      0x8024EFFF => "There was an expression evaluator error not covered by another WU_E_EE_* error code.",
      0x80243001 =>
        "The results of download and installation could not be read from the registry due to an unrecognized data format version.",
      0x80243002 =>
        "The results of download and installation could not be read from the registry due to an invalid data format.",
      0x80243003 =>
        "The results of download and installation are not available; the operation may have failed to start.",
      0x80243004 => "A failure occurred when trying to create an icon in the taskbar notification area.",
      0x80243FFD => "Unable to show UI when in non-UI mode; WU client UI modules may not be installed.",
      0x80243FFE => "Unsupported version of WU client UI exported functions.",
      0x80243FFF => "There was a user interface error not covered by another WU_E_AUCLIENT_* error code.",
      0x8024F001 => "The event cache file was defective.",
      0x8024F002 => "The XML in the event namespace descriptor could not be parsed.",
      0x8024F003 => "The XML in the event namespace descriptor could not be parsed.",
      0x8024F004 => "The server rejected an event because the server was too busy.",
      0x8024F005 => "The specified callback cookie is not found.",
      0x8024FFFF => "There was a reporter error not covered by another error code.",
      0x80247001 => "An operation could not be completed because the scan package was invalid.",
      0x80247002 =>
        "An operation could not be completed because the scan package requires a greater version of the Windows Update Agent.",
      0x80247003 => "An invalid event payload was specified.",
      0x80247004 => "The size of the event payload submitted is invalid.",
      0x80247005 => "The service is not registered.",
      0x80247FFF => "Search using the scan package failed.",
      0x8024B001 => "The task is currently in progress.",
      0x8024B002 => "The operation cannot be completed since the task status is currently disabled.",
      0x8024B003 => "The operation cannot be completed since the task is not yet started.",
      0x8024B004 => "The task was stopped and needs to be run again to complete.",
      0x8024B005 => "Cannot cancel a non-scheduled install.",
      0x8024B101 => "Hardware capability meta data was not found after a sync with the service.",
      0x8024B102 => "Hardware capability meta data was malformed and/or failed to parse.",
      _ => "Unknown Error: " + id
    };
  }
}
